# Generated by Django 3.1.7 on 2021-02-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name_of_dillers')),
                ('statistics_users', models.CharField(max_length=100, verbose_name='Statistics')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=255, verbose_name='User_name')),
                ('diller', models.ManyToManyField(to='stamp.Diller', verbose_name='Диллер')),
            ],
        ),
        migrations.CreateModel(
            name='Plotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField(max_length=1000, verbose_name='Статистика')),
                ('name_plotter', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('diller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.diller', verbose_name='Name_of_dillers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stamp.users', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mold', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=1, verbose_name='Размер')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('plotter_id', models.ManyToManyField(to='stamp.Plotter', verbose_name='Название')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
