# Generated by Django 3.1.7 on 2021-02-25 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('statistics_users', models.CharField(max_length=100, verbose_name='Statistics')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Plotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField(default='', max_length=1000, verbose_name='Статистика')),
                ('name', models.CharField(max_length=255, verbose_name='Имя плоттера')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('diller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamp.diller', verbose_name='diller_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=1, verbose_name='Размер')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('plotter_id', models.ManyToManyField(to='stamp.Plotter', verbose_name='plotter_id')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
