# Generated by Django 3.1.7 on 2021-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_of_user',
        ),
        migrations.AddField(
            model_name='user',
            name='login_user',
            field=models.CharField(default='', max_length=255, verbose_name='Login name'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='plotter_id',
            field=models.ManyToManyField(to='stamp.Plotter', verbose_name='Плоттер'),
        ),
    ]
