# Generated by Django 3.1.7 on 2021-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diller',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name_of_dillers'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='statistics',
            field=models.TextField(max_length=1000, verbose_name='Статистика'),
        ),
    ]
